### ISSUE TITLE
Minimalise and Maximalise doesn't work correctly.

### ISSUE THREAD

**Issue by Wadera** [Xelson/flarum-ext-chat#12]
It's kind of fixed. Working fine in "mobile view" on full screen, but failing on "desktop view": 
![image](https://user-images.githubusercontent.com/407236/145479925-307daf54-9b8e-495d-99f4-bcc25aa8d6f2.png)

_Originally posted by @Wadera in https://github.com/Xelson/flarum-ext-chat/issues/11#issuecomment-990304600_

**Comment by Xelson** [comment]
I have rejected this solution with chat maximization for a while and now the chat will adapt to the mobile screen size. Some features like chat filtering or message preview will not be available in mobile until I figure out how to arrange it all appropriately. Consider this a temporary solution.

**Comment by Wadera** [comment]
Fixed under 97a9ec9f4808e38e87f706843a32b524a57d22c0
