### ISSUE TITLE
New message texfield eating spaces

### ISSUE THREAD

**Issue by Wadera** [Xelson/flarum-ext-chat#13]
While typing new message on the chat, last space (after last word) sometimes disapper:

![Screen recording 2021-12-16 10 41 54](https://user-images.githubusercontent.com/407236/146347527-a245d647-2a6a-49a7-ae7b-33e4eb0679d2.gif)

**Comment by Xelson** [comment]
The same situation as with issue #14. I can't reproduce it, but corrected #13 and #14 in possible places. Check https://github.com/Xelson/flarum-ext-chat/commit/6d8734b3f1c76193d828136dffd6a41bcd4fe4bf

**Comment by Wadera** [comment]
Looks like fixed, but right now after sending message - text stays in textfield.

**Comment by Xelson** [comment]
ok, what about https://github.com/Xelson/flarum-ext-chat/commit/c23ff3cc31aaf6ebefec4b2f63070c9dc682be54?

**Comment by Wadera** [comment]
Fixed!

**Comment by Wadera** [comment]
but for some reason - mentions are gone 😱 
They are show on "preview" but don't display after sending message.

**Comment by Wadera** [comment]
It's working fine if adding space / text after mention.

**Comment by Xelson** [comment]
I think this is reason for another separate issue. And please relate the gif that show several cases of mentions usage
