### ISSUE TITLE
Chat texfield text is white on mobile

### ISSUE THREAD

**Issue by Wadera** [Xelson/flarum-ext-chat#14]
![Screenshot 2021-12-16 10 50 05](https://user-images.githubusercontent.com/407236/146348799-c8e6fb3c-79f9-4517-bc3e-26bda5e6f4aa.png)

It's looking fine on desktop (even in "mobile resolution")

**Comment by Xelson** [comment]
I can't reproduce it on the chronium and firefox engines, which browser do you use?

**Comment by Wadera** [comment]
Latest Google Chrome

**Comment by Wadera** [comment]
Fixed by 6d8734b3f1c76193d828136dffd6a41bcd4fe4bf
