### ISSUE TITLE
Realtime chat not working

### ISSUE THREAD

**Issue by datlechin** [Xelson/flarum-ext-chat#16]
![image](https://user-images.githubusercontent.com/56961917/146483717-f38093f9-489e-44f5-b728-7b379ae74c98.png)

**Comment by Xelson** [comment]
Have you enabled any sockets [Pusher](https://github.com/flarum/pusher) or [kyrne/websocket](https://github.com/kyrnedev/websocket)?
Have you set them up properly?

**Comment by datlechin** [comment]
> Have you enabled any sockets [Pusher](https://github.com/flarum/pusher) or [kyrne/websocket](https://github.com/kyrnedev/websocket)? Have you set them up properly?

yes, i have setup pusher

![image](https://user-images.githubusercontent.com/56961917/146504979-92becfd3-ccda-4b86-82c7-8af7fa850133.png)

**Comment by Xelson** [comment]
ok so let's try to send a message from another account.  It seems to me that the problem is messages from the socket are blocked based on the account ID, not the browser session

**Comment by datlechin** [comment]
it works with another account, but it doesn't work with another tab using the same account

**Comment by datlechin** [comment]
is this a bug or feature? 🤔🤔

**Comment by Xelson** [comment]
most likely this is a flaw. I will think about how to do it right and fix it in future commits
