### ISSUE TITLE
Uninstall not working

### ISSUE THREAD

**Issue by datlechin** [Xelson/flarum-ext-chat#20]
Got some errors when i try to uninstall this extension

```
POST http://localhost:8000/api/extensions/xelson-chat

PDOException: SQLSTATE[HY000]: General error: 1828 Cannot drop column 'removed_by': needed in a foreign key constraint 'neonchat_chat_user_removed_by_foreign' in /home/xxx/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
```

**Comment by Xelson** [comment]
Should be fixed in b97ffb279a4b5b46dafb322a12444ae5b7281efb. Please check

**Comment by datlechin** [comment]
Oki, thanks

**Comment by datlechin** [comment]
Hey, it's still same error
I tried run migrate and clear cache
But nothing change

**Comment by datlechin** [comment]
`PDOException: SQLSTATE[HY000]: General error: 3730 Cannot drop table 'neonchat_chats' referenced by a foreign key constraint 'neonchat_messages_chat_id_foreign' on table 'pushedx_messages'.`

**Comment by Xelson** [comment]
my bad, please try 5cd2c3527639d6c61c10f73364faba8e5004f4a1

**Comment by datlechin** [comment]
It's works now 🥰🥰
