### ISSUE TITLE
On mobile, the chat bar will overlap with the bottom bar of the mobile tab expansion

### ISSUE THREAD

**Issue by Xwdit** [Xelson/flarum-ext-chat#27]
On mobile, the chat bar will overlap with the bottom bar of the mobile tab expansion (And other elements that may be at the bottom), Is it possible to fix it?

**Comment by Xelson** [comment]
Fixed in https://github.com/Xelson/flarum-ext-chat/commit/79726139e5afe7c1d9b459516130752fcc8f9af9

**Comment by Xelson** [comment]
I reconsidered. I shouldn't have displayed the chat on top of modal windows and sidebars because this violates their principles of focusing attention and making decisions by the user. In the next update, the chat will overlap with these windows as before.
