### ISSUE TITLE
On Mobile, Chat List page not have minimize btn.

### ISSUE THREAD

**Issue by fanmingfei** [Xelson/flarum-ext-chat#28]
![image](https://user-images.githubusercontent.com/4632277/148637135-4a4d786d-d3ea-4fb7-b480-aac51fb1c7e2.png)

**Comment by datlechin** [comment]
Select a chat to minimize the Chat frame

**Comment by fanmingfei** [comment]
Thanks for your reply. I think it is necessary to close on this page. Because people are used to clicking the back button on the left top.

**Comment by fanmingfei** [comment]
BTW, Can i change this page's color ...

**Comment by datlechin** [comment]
> BTW, Can i change this page's color ...

this is hard to change quickly, but you can change some elements using css selectors

**Comment by JasonWung** [comment]
I have same issue question， it's uncomfortable operation.

**Comment by Xelson** [comment]
Fixed in https://github.com/Xelson/flarum-ext-chat/commit/48d73e741dcf03c876382a7e7d7506c3c3712e63
